version: '3'

services:
  web:
    build: ./docker
    volumes:
      - .:/var/www/html
      - ./docker/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    working_dir: /var/www/html
    restart: always
