// import "./settings/SettingsModule"
import './account/AccountModule';
import './admin/AdminModule';
import './application/ApplicationModule';
import './complete-registration/CompleteRegistrationModule';
import './filter/FilterModule';
import './forgot/ForgotModule';
import './mentorcity/MentorCityModule';
import './organizations/OrganizationModule';
import './page-not-found/PageNotFoundModule';
import './partner/PartnerModule';
import './partners/PartnersModule';
import './profile/ProfileModule';
import './programs/ProgramModule';
import './regions/RegionsModule';
import './reset/ResetModule';
import './results/ResultsModule';
import './searches/SearchesModule';
import './sign-in/SignInModule';
