import "./account/AccountModule"
import "./admin/AdminModule"
import "./application/ApplicationModule"
import "./complete-registration/CompleteRegistrationModule"
import "./feedback/FeedbackModule"
import "./filter/FilterModule"
import "./forgot/ForgotModule"
import "./organizations/OrganizationModule"
import "./partners/PartnersModule"
import "./profile/ProfileModule"
import "./programs/ProgramModule"
import "./regions/RegionsModule"
import "./reset/ResetModule"
import "./results/ResultsModule"
import "./search/SearchModule"
import "./searches/SearchesModule"
// import "./settings/SettingsModule"
import "./sign-in/SignInModule"
import "./partner/PartnerModule"
import "./mentorcity/MentorCityModule"

/** Catchall must be last **/
import "./page-not-found/PageNotFoundModule"
