export default class OrganizationFields {

  static readonly administrators = "field_administrators"
  static readonly altPhone = "alt_phone"
  static readonly description = "description"
  static readonly displayTitle = "title"
  static readonly email = "email"
  static readonly feedback = "feedback"
  static readonly firstName = "first_name"
  static readonly hasLocation = "has_location"
  static readonly importId = "field_import_id"
  static readonly lastName = "last_name"
  static readonly legalName = "legal_name"
  static readonly logo = "field_logo"
  static readonly mentorCityEnabled = "mentor_city_enabled"
  static readonly mtg = "field_mtg"
  static readonly mtgEnabled = "mtg_enabled"
  static readonly phone = "phone"
  static readonly physicalLocation = "location"
  static readonly position = "position"
  static readonly positionOther = "other_position"
  static readonly ready = "field_ready"
  static readonly session = "field_session"
  static readonly standing = "field_standing"
  static readonly taxStatus = "tax_status"
  static readonly taxStatusOther = "other_tax_status"
  static readonly type = "type"
  static readonly typeOther = "other_type"
  static readonly webAddress = "website"
  static readonly bbbscEnabled = "bbbsc_enabled"

}